language: rust

addons:
  apt:
    sources:
    - sourceline: 'ppa:giskou/librocksdb'
    packages:
    - libsnappy-dev
    - librocksdb

rust:
  # Feel free to bump this version if you need features of newer Rust.
  # Sync with badge in README.md
  - 1.23.0

matrix:
  allow_failures:
  - env: FEATURE=non-fatal-checks
  fast_finish: true

cache:
  cargo: true
  directories:
  - node_modules

dist: trusty
sudo: required

env:
  global:
  - CLIPPY_VERS=0.0.186
  - RUSTFMT_VERS=0.9.0
  - DEADLINKS_VERS=0.3.0
  - OUTDATED_VERS=0.7.0
  - SODIUM_VERS=1.0.16
  - RUSTFLAGS="-D warnings"
  - ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu
  - SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu
  matrix:
  - FEATURE=test

# Separate jobs should use `install` hook in order not to override these common
# instructions.
before_install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget "https://github.com/jedisct1/libsodium/releases/download/$SODIUM_VERS/libsodium-$SODIUM_VERS.tar.gz" -t 5 -O "libsodium.tar.gz"
    tar xvf libsodium.tar.gz
    cd libsodium-$SODIUM_VERS
    ./configure --prefix=$HOME/.local
    make
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig

jobs:
  include:
  # Formatting & other lints that do not require compilation
  - env: FEATURE=lints
    install:
    - rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
    - nvm install 8 && nvm use 8
    - npm install cspell
    - ./node_modules/.bin/cspell --version
    - npm install markdownlint-cli
    - ./node_modules/.bin/markdownlint --version
    script:
    - cargo fmt --all -- --write-mode=diff
    - ./node_modules/.bin/cspell {src,examples,tests}/**/*.rs
    - find . -not -path "./node_modules/*" -name "*.md" | xargs ./node_modules/.bin/cspell
    - find . -not -path "./node_modules/*" -name "*.md" | xargs ./node_modules/.bin/markdownlint --config .markdownlintrc

  # Clippy linting
  - env: FEATURE=clippy
    rust: nightly-2018-02-12
    install:
    - cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
    script:
    - cargo clippy --all -- -D warnings

  # Tests
  - env: FEATURE=test
    script:
    - cargo test --all

  # Non-fatal checks
  - env: FEATURE=non-fatal-checks
    install:
    - cargo-deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
    script:
    - cargo doc --no-deps
    - cargo deadlinks --dir target/doc

notifications:
  slack:
    secure: iybTEOGjMdmK+EWGcwX4ST43pdo8zqN5NjuREbpZJUXSaAtpqKYYNSAzLO89HH60NgMVLN6AfNgq73TL2kmF/f2Nz3XEsEpeaOGTBA53gbodwEgfP6hDWqFpG2Za6zKMZs99TIZXMDD061WUQAOJLpJ8RFEtixcBoNTm5P019X9sTTAdCND6qoByuHDp43S+RUn9vbak4aYCqKAcxxsnCV6WtC21/jTjluzgofRwtHYrw7hmC8cKBD+1cMpg/kPD6qvfX/PoZ+oFx+IMIuVrLQ49De908517eNEd6IJDfz/T5LQT10F7gTYhwdnTLrYRwEkl3K2XzeDTDoxhATrWcyQlexl0MQ+o+cdzVNKNxK0NoJPruJ1vXxfIl7PvhbF+sbR/Rmju03CC+e2EDFLw5P6IP++neHWzD75vfeOie7PNfwvJZpsd5yopivPB4qXOHiIWi2vXOLt8fiT4cNs4qW+9e1DhniuJnnNf4Jxg078Vh/c5gqyFBG/I2eyl3RnTlGIpH9EqTsS3BzdjWqKC24e61HdGt7F/U8BA3G/raPSoz7dZbOxFWW6dLbxMCUAO4qpQLNfgPV3fpbDB+87pYUipkUhU5aRL9mRlCwDGCoaB6jSFQDIgka/6CGoZAiIIneZWmV0xFMwjSL4vh5nn6M/I+3I51B/YhkEy7jm2rG8=
