[package]
name = "btc-transaction-utils"
description = "A collection of helpers for signing bitcoin transactions with segwit."
version = "0.1.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
readme = "README.md"
repository = "https://github.com/exonum/btc-transaction-utils"
documentation = "https://docs.rs/btc-transaction-utils"
categories = ["cryptography"]
keywords = ["crypto", "bitcoin", "segwit"]

[dependencies]
bitcoin = { version = "0.13.0" }
display_derive = "0.0.0"
failure = "0.1.1"
failure_derive = "0.1.1"
hex = "0.3.1"
rand = "0.4.0"
secp256k1 = { version = "0.9.0", features = ["rand"] }
serde = "1.0.37"
serde_str = "0.1.0"
pretty_assertions = "0.5.1"