[package]
name = "bitcoin-transactions-builder"
version = "0.0.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
readme = "README.md"

[dependencies]
bitcoin = { version = "0.12.0", features = ["bitcoinconsenus"] }
display_derive = "0.0.0"
failure = "0.1.1"
failure_derive = "0.1.1"
hex = "0.3.1"
rand = "0.4.0"
secp256k1 = { version = "0.9.0", features = ["rand"] }
serde = "1.0.37"
serde_str = "0.1.0"