[package]
name = "bitcoin-transactions-builder"
version = "0.0.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
readme = "README.md"

[dependencies]
bitcoin = "0.12.0"
serde = "1.0.37"
serde_str = "0.1.0"